name: clientserver
version: 0.1.0
description: A sample application showing App Engine code sharing between client and server.
dependencies:
  shelf_appengine: ">=0.2.0 <0.3.0"
  shelf_route: ">=0.11.0+1 <0.12.0"
  browser: '>=0.10.0 <0.11.0'
transformers:
- $dart2js:
    $exclude: bin/**.dart
