name: clientserver
version: 0.1.0
description: A sample application showing App Engine code sharing between client and server.
dependencies:
  appengine: '>=0.2.1 <0.3.0'
  browser: '>=0.10.0 <0.11.0'
transformers:
- $dart2js:
    $exclude: bin/**.dart
