name: todos
version: 0.1.0
description: A sample application showing App Engine code sharing between client and server.
dependencies:
  shelf_appengine: ">=0.2.0 <0.3.0"
  shelf_route: ">=0.11.0+1 <0.12.0"
  polymer: '>=0.15.5+3 <0.16.0'
  paper_elements: '>=0.6.1 <0.7.0'
transformers:
- polymer:
    entry_points: web/index.html
    inline_stylesheets:
      web/css/app.css: false 
